site_name: Cubow Documentation
theme:
  name: 'material'
  palette:
    primary: '#e166fd'
    accent: '#7739fb'
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/Vr8X2Wteje
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - FAQ: faq.md
  - Commands: commands.md
  - Option Commands: options.md
  - Tickets: tickets.md
  - How To Use AI: ai-setup.md